import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export async function getServerSideProps(){
  const resp = await fetch("https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json");
    
    return {
      props: {
        pokemon: await resp.json(),
      }
    }
}

export default function Home({ pokemon }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>{JSON.stringify(pokemon)}</div> */}
<div><h2>Pokemon List</h2></div>
      <div className={styles.gridone}>
        { pokemon.map((pokemon) => (

      <div className={styles.cardone} key={pokemon.id}>

      <Link href={`/pokemon/${pokemon.id}`}>
          <img
          src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`}
          alt={pokemon.name}
          
          />
          <h3>{pokemon.name}</h3>

      </Link>
      </div>

        ))}

      </div>


          

          </div>
  )
}
